cookie:
  expiry_days: 30
  key: aeeddd77dba96da6d12ee097cc7dc93d5aff59bd75709a67e475c2190f0be3ed
  name: sclca_fm_auth
credentials:
  usernames:
    carl:
      email: carl@terayoncapital.com
      first_name: Carl
      last_name: Liebenberg
      password: $2b$12$NxIMJV7uVeK9ocO2cyoTpeCk/4ydGRqL93V7948Ep9yRMVjGnuxv6
      permissions:
        can_manage_users: false
        entities:
        - '*'
        mgmt_pages: []
        tabs:
        - '*'
      roles:
      - promotor_opco
    eckardt:
      email: eckardt@vansquared.co.za
      first_name: Eckardt
      last_name: van Wyk
      password: $2b$12$L.TrJK.p5qK2eDiPjNLdU.OTTaiQh1lRZW7DZNgrjwMfwUpiBAIMi
      permissions:
        can_manage_users: false
        entities:
        - Catalytic Assets
        - Timberworx
        mgmt_pages: []
        tabs:
        - '*'
        - Pipeline
      roles:
      - promotor_opco
    mark:
      email: m.vanhouten@nexusnovus.com
      first_name: Mark
      last_name: van Houten
      password: $2b$12$8VClwb2bGd5nyW3yUW3afOGxJVBFqCQbNN03lV9RBhuHHeIcnuNh2
      permissions:
        can_manage_users: false
        entities:
        - '*'
        mgmt_pages:
        - '*'
        tabs:
        - '*'
        - Pipeline
      roles:
      - promotor_opco
    rmdebruijn@nexusnovus.com:
      email: rmdebruijn@nexusnovus.com
      first_name: Rutger
      last_name: de Bruijn
      password: $2b$12$wOuXzxmw8WSpP8WX5rsUg.HhJ5UCY0B7CtEZ82o3ZqYEcnrEFxnQu
      roles:
      - admin
    robbert:
      email: r.zappeij@zencustomerfinance.nl
      first_name: Robbert
      last_name: Zappeij
      password: $2b$12$TS4iMkXMx0oP49kQr64oMOYGD84mQA4RkcQspmLT3w5tfdjXwIuiu
      permissions:
        can_manage_users: false
        entities:
        - '*'
        mgmt_pages:
        - Guarantor Analysis
        tabs:
        - '*'
        - Pipeline
      roles:
      - promotor_opco
    rutger:
      email: rutger@nexusnovus.com
      first_name: Rutger
      last_name: Admin
      password: $2b$12$wOuXzxmw8WSpP8WX5rsUg.HhJ5UCY0B7CtEZ82o3ZqYEcnrEFxnQu
      roles:
      - admin
    saskia:
      email: s.bruinders@nexusnovus.com
      first_name: Saskia
      last_name: bruinders
      password: $2b$12$Ws1.iQ56Uh/cCtyhW9Scju36bWBkroUt554jA8wa2TQz6S9n5rHyW
      permissions:
        can_manage_users: false
        entities:
        - '*'
        mgmt_pages: []
        tabs:
        - '*'
        - Pipeline
      roles:
      - promotor_opco
    siza:
      email: sizakelem@crosspointproperty.co.za
      first_name: Sizakele
      last_name: Mabuza
      password: $2b$12$cfGkTS01dCymNpwxMXQ21eerq577rZBJmHGQyd5Fi/Il8vpodXJI2
      permissions:
        can_manage_users: false
        entities:
        - '*'
        mgmt_pages:
        - Summary
        - Strategy
        - Tasks
        - CP & CS
        tabs:
        - '*'
      roles:
      - promotor_opco
    werner:
      email: werner@greenblock.co.za
      first_name: Werner
      last_name: Slabbert
      password: $2b$12$.dV7UZvsdQnOfzVC14dZt.DF1WaPwIEY0F3mz3veXISyUO6tRaqK6
      permissions:
        can_manage_users: false
        entities:
        - Timberworx
        mgmt_pages: []
        tabs:
        - '*'
        - Pipeline
      roles:
      - promotor_opco
