cookie:
  expiry_days: 30
  key: aeeddd77dba96da6d12ee097cc7dc93d5aff59bd75709a67e475c2190f0be3ed
  name: sclca_fm_auth
credentials:
  usernames:
    rmdebruijn@nexusnovus.com:
      email: rmdebruijn@nexusnovus.com
      first_name: Rutger
      last_name: de Bruijn
      password: $2b$12$qI8GeiloVsBXqAzARxJTm.MfjyN86TLzognFgIcoVPkAUmpG/lk1a
      roles:
      - admin
    rutger:
      email: rutger@nexusnovus.com
      first_name: Rutger
      last_name: Admin
      password: $2b$12$CNzigKxJLc5vsA6rVLif0ehcUGtCMUS8C5CI9UFx7MI0Kv.VBvG0.
      roles:
      - admin
